data:
  path_features: 'data/elliptic_bitcoin_dataset/elliptic_txs_features.csv'
  path_edgelist: 'data/elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv'
  path_classes: 'data/elliptic_bitcoin_dataset/elliptic_txs_classes.csv'


gat:
  hidden_dim: 64
  embedding_dim: 128
  n_layers: 3
  n_features: 166
  output_dim: 2
  dropout_rate: 0.6
  heads: 5

  lr: 0.01
  epochs: 500
  batch_size: 128

  path_model: 'model/gat/model.pt'

  test:
    n_random_samples: 1000
    path_results: 'model/gat/results.csv'


logger:
  log_dir: 'logs/'
  log_clear_days: 20

device_id: 0

tensorboard:
  log_dir: 'runs/gat_version_1'
