data:
  path_features: 'data/elliptic_bitcoin_dataset/elliptic_txs_features.csv'
  path_edgelist: 'data/elliptic_bitcoin_dataset/elliptic_txs_edgelist.csv'
  path_classes: 'data/elliptic_bitcoin_dataset/elliptic_txs_classes.csv'


gat:
  hidden_dim: 64
  embedding_dim: 128
  n_layers: 3
  dropout_rate: 0.6
  lr: 0.01
  n_epochs: 500
  heads: 5


logger:
  log_dir: 'logs/'
  log_clear_days: 20

device: 0

tensorboard:
  log_dir: 'runs/gat_version_1'
